server:
  port: 8090
  max-http-request-header-size: 1048576

spring:
  profiles:
    active: dev

  datasource:
    master:
      url: ${application.datasource.master.url}
      username: ${application.datasource.master.username}
      password: ${application.datasource.master.password}
      driver-class-name: ${application.datasource.master.driver-class-name}

    slave:
      url: ${application.datasource.slave.url}
      username: ${application.datasource.slave.username}
      password: ${application.datasource.slave.password}
      driver-class-name: ${application.datasource.slave.driver-class-name}

    hikari:
      minimum-idle: ${application.datasource.hikari.minimum-idle}
      maximum-pool-size: ${application.datasource.hikari.maximum-pool-size}
      pool-name: ${application.datasource.hikari.pool-name}
      idle-timeout: ${application.datasource.hikari.idle-timeout}
      max-lifetime: ${application.datasource.hikari.max-lifetime}

  redis:
    master:
      host: ${application.redis.master.host}
      port: ${application.redis.master.port}
      password: ${application.redis.master.password}
    slave:
      host: ${application.redis.slave.host}
      port: ${application.redis.slave.port}
      password: ${application.redis.slave.host}

  aws:
    s3:
      accesskey: mXWS1OkSfUcoklnZ
      secretkey: zWL5n36GRVYqSHS1VLxOQRuCL6tsLjBD
      region: auto
      endpoint: https://resources.meetingforyou.site
      bucket: meeting-for-you
      path-style-access: true

  mybatis:
    mapper-locations: ${application.mybatis.mapper-locations}
    type-aliases-package: ${application.mybatis.type-aliases-package}
    configuration:
      log-impl: ${application.mybatis.configuration.log-impl}

