application:
  datasource:
    master:
      url: jdbc:mysql://47.130.53.29:3306/meeting-for-you
      username: root
      password: liuxingzhao
      driver-class-name: com.mysql.cj.jdbc.Driver

    slave:
      url: jdbc:mysql://47.130.53.29:3307/meeting-for-you
      username: root
      password: liuxingzhao
      driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: DBPool
      idle-timeout: 30000
      max-lifetime: 600000

  redis:
    master:
      host: 47.130.53.29
      port: 6379
      password: liuxingzhao
    slave:
      host: 47.130.53.29
      port: 6380
      password: liuxingzhao

  jwt:
    secretkey: VHJ1c3R3b3JrT3BhZHVzJTIwU2VjdXJlU2VjcmV0Q29tcGxleEJ0b2xkY29tcGxleENvbmZpZyUyMExhcmdlU2VjcmV0S2V5
    freshTokenExpiration: 2592000000 #30 days
    accessTokenExpiration: 25920000000 # 30 days
    token-name: Authorization
    uid: uid # Private token claims
    role: role

  mybatis:
    mapper-locations: classpath:backend/mapper/*.xml
    type-aliases-package: backend.model.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl